name: basic_checks

on: [push]

concurrency:
  group: test-${{ github.head_ref }}
  cancel-in-progress: true

env:
  PYTHONUNBUFFERED: "1"
  FORCE_COLOR: "1"

permissions:
  contents: read

jobs:

  run:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Install uv
        uses: astral-sh/setup-uv@v8.1.0
        with:
          enable-cache: true

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version-file: ".python-version"

      - name: Install the project
        run: uv sync --all-packages --all-extras --dev

      - name: Format
        uses: astral-sh/ruff-action@v3
        with:
          args: "format --check"

      - name: Type check
        run: uv run --with=pip mypy --install-types --non-interactive src

      - name: Static analysis
        uses: astral-sh/ruff-action@v3
        with:
          args: "check"

      - name: Minimize uv cache
        run: uv cache prune --ci
